# Generated by Django 6.1.1 on 2026-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Error Analysis', max_length=255)),
                ('raw_error', models.TextField()),
                ('code_context', models.TextField(blank=True, default='', null=True)),
                ('file_type', models.CharField(default='text', max_length=50)),
                ('framework', models.CharField(default='Auto-Detect', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('code_suggestion', models.TextField(blank=True, default='')),
                ('matched_kb_items', models.JSONField(blank=True, default=list)),
                ('ai_model_used', models.CharField(default='Smart RAG + AI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('error_pattern', models.TextField(help_text='Key error terms, exceptions, or patterns to match')),
                ('category', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('JavaScript', 'JavaScript / React'), ('Database', 'Database / SQL'), ('DevOps', 'DevOps / Docker / K8s'), ('Security', 'Security & Auth'), ('API', 'REST API & Web'), ('General', 'General / Other')], default='General', max_length=100)),
                ('explanation', models.TextField(help_text='Simple ELI5 explanation of the error')),
                ('solution_steps', models.TextField(help_text='Practical step-by-step instructions to resolve')),
                ('code_example', models.TextField(blank=True, default='', help_text='Corrected code example or snippet')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='System Built-in', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('groq_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_provider', models.CharField(default='auto', max_length=50)),
                ('rag_top_k', models.IntegerField(default=3)),
                ('temperature', models.FloatField(default=0.2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
